# Get your API key from https://platform.openai.com/account/api-keys
# 1. Sign in to your OpenAI account
# 2. Go to https://platform.openai.com/account/api-keys
# 3. Click "Create new secret key"
# 4. Copy the key and paste it below
# 5. Save this file
# 6. Restart your Streamlit app

<<<<<<< HEAD
OPENAI_API_KEY = "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"

# Google Drive Model URLs
[model_urls]
breast_cancer_model = "https://drive.google.com/uc?id=1oUCacUPYAemX0zCJbRpVXutSjFtgac4K"
disease_model = "https://drive.google.com/uc?id=1h3RYnCvYNeE0HltyzVisU67DuTvaAdVf"

# Application Configuration
[app_config]
app_name = "Health Prognosis"
description = "Get personalized predictions for various health conditions using advanced machine learning models."

# Email Configuration
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "healthprognosis@gmail.com"
# Replace this with the 16-character App Password generated from Google Account
sender_password = "your-16-character-app-password" 
=======
OPENAI_API_KEY = "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" 
>>>>>>> b63058c4fa6ed5033f5e71df049712721559b884
