# Get your API key from https://platform.openai.com/account/api-keys
# 1. Sign in to your OpenAI account
# 2. Go to https://platform.openai.com/account/api-keys
# 3. Click "Create new secret key"
# 4. Copy the key and paste it below
# 5. Save this file
# 6. Restart your Streamlit app

OPENAI_API_KEY = "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" 